esphome:
  name: pm2k-devel-esp32
  project:
    name: "dj1975-se.plantmaster20000"
    version: "2.2.1"

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# Wifi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

# mdns needed for proper OTA
mdns:
  disabled: false

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encrkey
  reboot_timeout: 480min
  id: !secret esphomename

ota:
  safe_mode: true
  password: !secret ota_password
  on_begin:
    then:
      - logger.log: "OTA start"
  on_progress:
    then:
      - logger.log:
          format: "OTA progress %0.1f%%"
          args: ["x"]
  on_error:
    then:
      - logger.log:
          format: "OTA update error %d"
          args: ["x"]
  on_end:
    then:
      - logger.log: "OTA end"

# i2c bus setup
i2c:
  sda: !secret i2csda_pin
  scl: !secret i2cscl_pin
  scan: true
  id: bus_a

dallas:
  - pin: !secret dallasbus_pin
    update_interval: !secret updateinterval

sensor:
  - platform: adc
    pin: GPIO34
    name: "GPIO34"
    attenuation: auto
    update_interval: !secret updateinterval

  - platform: adc
    pin: GPIO32
    name: "GPIO32"
    attenuation: auto
    update_interval: !secret updateinterval

  - platform: adc
    pin: GPIO33
    name: "GPIO33"
    attenuation: auto
    update_interval: !secret updateinterval

  - platform: htu21d
    temperature:
      name: "SHT21 Temperature"
    humidity:
      name: "SHT21 Humidity"
    update_interval: !secret updateinterval

  - platform: bh1750
    name: "BH1750 Illuminance"
    address: 0x23
    update_interval: !secret updateinterval

  - platform: dallas
    address: !secret ds18b20-1_address
    name: "ds18b20 Temperature"

  - platform: wifi_signal
    name: "WiFi RSSI"
    update_interval: !secret updateinterval

switch:
  - platform: gpio
    pin: GPIO16
    name: "ESP32 GPIO16"

