esphome:
  name: triplewhammy-esp32
  project:
    name: "dj1975.plantmaster2000"
    version: "4.2.3"

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

mdns:
  disabled: false

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encrkey
  reboot_timeout: 480min
  id: "triplewhammy_esp32"

ota:
  safe_mode: true
  password: !secret ota_password
  on_begin:
    then:
      - logger.log: "OTA start"
  on_progress:
    then:
      - logger.log:
          format: "OTA progress %0.1f%%"
          args: ["x"]
  on_error:
    then:
      - logger.log:
          format: "OTA update error %d"
          args: ["x"]
  on_end:
    then:
      - logger.log: "OTA end"

i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a

dallas:
  - pin: !secret dallasbus_pin
    update_interval: !secret updateinterval

ads1115:
  - address: 0x48

sensor:
#  - platform: adc
#    pin: GPIO34
#    name: "GPIO34"
#    attenuation: auto
#    update_interval: !secret updateinterval

#  - platform: adc
#    pin: GPIO32
#    name: "GPIO32"
#    attenuation: auto
#    update_interval: !secret updateinterval

#  - platform: adc
#    pin: GPIO33
#    name: "GPIO33"
#    attenuation: auto
#    update_interval: !secret updateinterval

  - platform: htu21d
    temperature:
      name: "SHT21 Temperature"
    humidity:
      name: "SHT21 Humidity"
    update_interval: !secret updateinterval

  - platform: bh1750
    name: "BH1750 Illuminance"
    address: 0x23
    update_interval: !secret updateinterval

  - platform: dallas
    address: !secret ds18b20-1_address
    name: "ds18b20 Temperature 1"

  - platform: dallas
    address: !secret ds18b20-2_address
    name: "ds18b20 Temperature 2"

  - platform: dallas
    address: !secret ds18b20-3_address
    name: "ds18b20 Temperature 3"

  - platform: ads1115
    multiplexer: 'A0_GND'
    name: "ads1115 a0"
    gain: 2.048
    update_interval: !secret updateinterval

  - platform: ads1115
    multiplexer: 'A1_GND'
    name: "ads1115 a1"
    gain: 2.048
    update_interval: !secret updateinterval

  - platform: ads1115
    multiplexer: 'A2_GND'
    name: "ads1115 a2"
    gain: 2.048
    update_interval: !secret updateinterval

  - platform: ads1115
    multiplexer: 'A3_GND'
    name: "ads1115 a3"
    gain: 2.048
    update_interval: !secret updateinterval

  - platform: wifi_signal
    name: "WiFi RSSI"
    update_interval: !secret updateinterval

switch:
  - platform: gpio
    pin: 16
    name: "ESP32 GPIO16"

